name: PR Build

on:
  pull_request:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Compile code
      run: npm run build || echo "Build script not implemented"

    - name: Secret scanning with TruffleHog
      uses: trufflesecurity/trufflehog-action@v1
      with:
        scan_depth: 50

    - name: Dependency scanning
      run: npm audit --production
